name: dart_canvas_player
version: 1.0.0
description: >-
  Do you have want to record a Canvas element?
homepage: https://github.com/eatsjobs/dart-canvas-player

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js: ^0.6.0
  html: ^0.14.0+3

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.14.2
